
server:
  port: 8081

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          default-label: config-server
          # default-label: config-service
          uri: https://github.com/m44rx/pp-server
          search-paths:
          - config-data
          # - pp-server
